# Generated by Django 5.0.6 on 2024-05-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='user_response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='place_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
