# Generated by Django 5.0.6 on 2024-05-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_user_info_delete_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='name',
        ),
    ]
