# Generated by Django 5.0.6 on 2024-05-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_user_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='place_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
