# Generated by Django 4.1.13 on 2024-06-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_user_info_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='place_type',
            field=models.CharField(default='restaurant', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
