# Generated by Django 4.1.13 on 2024-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_remove_user_info_place_id_remove_user_info_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='place_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
