# Generated by Django 4.1.13 on 2024-06-02 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_user_info_place_type_alter_user_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
