# Generated by Django 4.1.13 on 2024-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_userplacemapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
