# Generated by Django 4.1.13 on 2024-06-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_user_info_latitude_user_info_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
