# Generated by Django 4.1.13 on 2024-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_restaurantsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsname',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsname',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
